### ISSUE TITLE
List of built-in commands

### ISSUE THREAD

**Issue by Arkadeep-sophoIITG** [PradyumnaAtGithub/Minishell#1]
Can you please provide a list of built-in commands that the shell supports?

**Comment by pradykaushik** [comment]
The minishell supports most of the commands supported by a regular shell.
For example,
* ls
* ps
* cd
* cat
...

**Comment by Arkadeep-sophoIITG** [comment]
Any custom commands implemented?

**Comment by pradykaushik** [comment]
Job control is a shell feature, so when you're writing your own shell, you will need to implement job control, which has been implement here. Also, 'cd' is a command that again needs to be implemented by you alone as there doesn't exist a corresponding binary.

**Comment by Arkadeep-sophoIITG** [comment]
It doesn't support &&, || operators with commands, right?

**Comment by Arkadeep-sophoIITG** [comment]
Why does memory corruption error occur on commands of length greater than 30 characters ?

**Comment by pradykaushik** [comment]
I haven't personally tested for && and || but I feel they should work.

**Comment by pradykaushik** [comment]
> Why does memory corruption error occur on commands of length greater than 30 characters ?

Can you mention the command that you're trying to execute?

**Comment by Arkadeep-sophoIITG** [comment]
rm $(ls -I "*.txt") works !! (Deletes all files in a directory except .txt extension)
But when I include multiple extensions rm $(ls -I "*.txt" -I "*.pdf") , memory corruption error arises and core dumped!! Even when I do mkdir (dir name(>25 chars)) ,same error arises.

Uploaded screenshot!!
![screenshot from 2017-09-29 12 01 29](https://user-images.githubusercontent.com/19313432/31003573-0cfe36fe-a50e-11e7-8bd1-633412781b40.png)

**Comment by pradykaushik** [comment]
This issue seems to be linked with the Perl regex library. @ajain13 will be able to give a better explanation on this but from what I recall, that regex library has issues and is deprecated.
I would gladly welcome a patch to fix this issue.
